remote_theme: emmacarli/bay

title: Emma Carli



header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Research  # <-- research.md
    - name: Blog  # <-- blog.md

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: emma.carli@postgrad.man.ac.uk
      link: mailto:emma.carli@postgrad.manchester.ac.uk

  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/emmacarli
    - name: GitHub
      link: http://github.com/emmacarli
    - name: ResearchGate
      link: https://www.researchgate.net/profile/Emma_Carli2
    - name: Manchester U.
      link: https://www.research.manchester.ac.uk/portal/en/researchers/emma-carli(1f63fe27-26ec-4429-a24b-e6ea6a03a63d).html
    - name: ORCiD
      link: https://orcid.org/0000-0003-3265-2866
